### ISSUE TITLE
What should I do after finish running two python files?

### ISSUE THREAD

**Issue by jimchenhub** [ysyushi/aspem#1]
Hello! Thanks for this wonderful job. I'm trying to follow the instruction that described in your paper as follows:

1. selecting a set of representative aspects for the HIN of interest, 
2. learning embedding vectors for each aspect
3. integrating embeddings from multiple aspects.

Now I have finished running two python files
```
$ python src/calc_base_aspect_inconsistency.py --input data/imdb/imdb.hin --output data/imdb/imdb_base_aspect_inc.csv 
$ python src/agg_aspect_inconsistency.py $data/imdb/imdb_base_aspect_inc.csv 
```
which the output is 
```
Nodes {'a', 'u', 'm'} Edges ['a', 'u']
Inc 171.607
Nodes {'d', 'g', 'm'} Edges ['d', 'g']
Inc 531.266
Nodes {'g', 'u', 'm'} Edges ['g', 'u']
Inc 636.442
Nodes {'d', 'a', 'm'} Edges ['d', 'a']
Inc 1689.76
Nodes {'d', 'u', 'm'} Edges ['d', 'u']
Inc 1927.68
Nodes {'d', 'g', 'u', 'm'} Edges ['d', 'g', 'u']
Inc 3095.388
Nodes {'d', 'a', 'u', 'm'} Edges ['d', 'a', 'u']
Inc 3789.047
Nodes {'a', 'g', 'm'} Edges ['a', 'g']
Inc 12956.6
Nodes {'a', 'g', 'u', 'm'} Edges ['a', 'g', 'u']
Inc 13764.649000000001
Nodes {'d', 'g', 'a', 'm'} Edges ['d', 'a', 'g']
Inc 15177.626
Nodes {'m', 'd', 'g', 'a', 'u'} Edges ['d', 'a', 'g', 'u']
Inc 17913.355
```

In my understanding, these two python files correspond to the first step in instruction. 

So what confused me is

1. What is the output mean?
2. And what should I do to follow the second step in instruction? (or how can I use `emb_imdb` base on these outputs?)

**Comment by ysyushi** [comment]
Thank you for your interests!

> In my understanding, these two python files correspond to the first step in instruction.

This is correct.

> 1. What is the output mean?

It gives you the incompatibility  score of each candidate aspect described in the paper. You can select aspect to embed based on these scores.

> 2. And what should I do to follow the second step in instruction? (or how can I use emb_imdb base on these outputs?)

As discussed in the paper, users have the freedom to choose different embedding algorithms. You could use emb_imdb as the default option.
